// locale/zh.js
export default ({
   hello: '你好，{name}',
   "Network Center":"网络中心",
   "ReadySHARE":"文件共享",
   "vPort":"端口",
   "Diagnosis":"症断",
   "Setting":"设置",  "setting":"设置",
   "state":"状态",
   "wireless":"无线",
   "Internet":"互联网",
   "localNetwork":"本地网络",
   "parentalCtrl":"家长控制",
   "flowCtrl":"流量控制",
   "security":"安全性",
   "noticeSettings":"通知设置",
   "management":"管理",
   "Remote Router":"远程路由器",
   "vPath":"路径",

   "vPath packs":"路径包",
   "payment":"支付",

   "Manage Server":"管理服务器",
   "Management Goal":"管理目标",
   "Syslog":"系统日志",                         "System log":"系统日志",
   "Address":"地址",
   "Port":"端口",
   "test":"测试",
   "save":"保存",
   "Level":"等级",
   "Enable":"启动",
   "Expiration date":"到期时间",
   "Please click to pay":"支付请点击",
   "close":"关闭",
   "refresh":"刷新",
   "Virtual":"虚拟", "virtual":"虚拟",
   "Add New":"添加",
   "Boot Nodes":"引导节点",
   "Remote Virtual IP":"远程虚拟IP",
   "Remote Subnet":"远程子网",
   "Link State":"链路状态",
   "delay":"延时",
   "description":"描述",
   "Please input keywords or domain or URL":"请输入关键字或域名或URL",
   "vPath_title":"来自vPort{idNum}的域名的流量将通过所选的vProxy路由。",
   "Add":"增加",
   "domain":"域名",
   "proxy":"代理",
   "vPathPacks_title":"vPathPacks:请选择一个要编辑的vPathPack",
   "Already Online":"已联机",
   "Gateway":"网关",
   "Server":"服务器",
   "Name":"名称",
   "Safe Mode":"安全模式",
   "Device List":"设备列表",
   "Memory":"内存",
   "Enable wireless broadcast":"启用无线广播",
   "Show":"显示",
   "Hide":"隐藏",
   "Security Level":"安全级别",
   "Guest Network":"访客网络",
   "Filter":"过滤器",
   "Password":"密码","password":"密码",
   "Wireless Mode":"无线模式",
   "Advanced Options":"高级选项",

   "wps_tab_desc":"您可以使用WPS(Wi-Fi Protected Setup)以在Synology Router与无线客户端之间共享无线密钥，并通过以下方法之一安全地建立无线网络。",
   "Connection State":"连接状态",
   "Ready":"已就绪",
   "Connection Type":"连接类型",
   "By Push Button":"通过推送按钮",
   "":"",
   "":"",
   "":"",
   "":"",

   "workMode_desc":"您如何设置 Synology Router 的网络映射？要了解更多信息，请参考SRM帮助。",
   "Plan":"计划",                       "Work Mode":"工作模式",
   "Update And Reset":"更新和还原",     "Default Port Number":"默认端口号",
   "System Name":"系统名称",            "Region Options":"区域选项",
   "Using State":"使用状态",
   "Enable SSH Functionality":"启动SSH功能",
   "Wireless Router":"无线路由器",
   "Wireless access point":"无线接入点",
   "Wireless client":"无线客户端",
   "Firewall":"防火墙",        "firewall":"防火墙",
   "Auto Block":"自动封锁",
   "Certificate":"证书",
   "Email":"电子邮件",
   "Message":"短信",
   "Push Service":"推送服务",
   "Advanced Setting":"高级设置",


 });
